### ISSUE TITLE
Is it functional?

### ISSUE THREAD

**Issue by jcubic** [cgorringe/RIPtermJS#2]
I was just reading about RIPScript and was searching for JavaScript implementation. But when tested the demo (in the latest Firefox and Chrome) it didn't work. Only the diff and screenshot show up.

Is this a working project?

**Comment by cgorringe** [comment]
Yes it works!

Try these steps:
1. Select RIP file from the drop down.
2. Tap **Load RIP**
3. Tap **Start**

**Comment by jcubic** [comment]
Thanks, I assumed that load would run the code.
